# Generated by Django 4.0.4 on 2022-04-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_available_count',
            field=models.IntegerField(default=0),
        ),
    ]
